#pragma once

#include <iostream>
#include <cstring>
#include <string>



using namespace std;

class User
{

private:
    string name;
    int userID; //generated by default
    string password;
    public : static int counterUser ;

public:
    User();
    User(string n, string pass);
    User(string n, string pass, int id);

    ~User();
    void setName(string userName);
    string getName();
    void setPassword(string userPassword);
    string getPassword();
    bool displayed=false;
    void setdisplayed();
    int getUserID();
    static int getCounterUser();
    static void setCounterUser(int count);
    friend std::ostream& operator<<(std::ostream& os, const User& u) {
        os << u.name << " " << u.userID << " " << u.password;
        return os;
    }
    bool operator==(const User& other) const;
};






